### PR TITLE
Extra readme text

### PR DESCRIPTION
**Pull request by JulieKate61**
Make some comments and add extra text to this 'branch' of the master
@jessicacork
@CameronRBarrie

### CODE REVIEW

**Comment by CameronRBarrie** [comment]
`tuple` anyone

I'm thinking a 'tipple' would be better

**Comment by jessicacork** [comment]
I'm going to attach a file and see how that goes :)
[SCImago2014_Q1.xlsx](https://github.com/JulieKate61/Hello_World/files/496772/SCImago2014_Q1.xlsx)

**Comment by jessicacork** [comment]
So do we all have 'write access'?

**Comment by JulieKate61** [comment]
We are all participants in this 'branch' off the master.  I'm not sure if this discussion becomes the final merged text once it gets committed...?  A lot of new concepts to consider.

**Pull request merged**
